[package]
name = "atomblocks"
version = "0.3.0"
edition = "2021"
license-file = "LICENSE"
description = "async, absolutely lightweight and dead simple bar for dwm and similar window managers"
readme = "README.md"
homepage = "https://github.com/milchinskiy/atomblocks"
repository = "https://github.com/milchinskiy/atomblocks"
keywords = ["utils", "bar", "x11"]
categories = ["command-line-utilities", "os"]

[dependencies]
argh = { version = "0.1" }
libc = { version = "0.2" }
log = { version = "0.4", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
simple_logger = { version = "4", features = [
  "colored",
  "stderr",
], default-features = false }
toml = { version = "0.8", default-features = false, features = ["parse"] }
x11rb = { version = "0.13" }

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1
